packages: []

catalogs:
  kitql:
    "@kitql/eslint-config": 0.7.0
    "@kitql/handles": 0.3.0
    "@kitql/helpers": 0.8.12
    "@kitql/internals": 0.10.3
    "@kitql/sveltekit": 0.0.4

  vite: 
    vite-plugin-kit-routes: 1.0.0
    vite-plugin-stripper: 0.9.0
    vite-plugin-watch-and-run: 1.7.4
  
  remult: 
    remult: 3.1.0
    firstly: 0.2.0
  
  devDeps: 
    "@sveltejs/kit": 2.30.1
    "@sveltejs/vite-plugin-svelte": 6.1.0
    node-modules-inspector: 1.0.0
    typescript: 5.9.2
    vite: 7.1.0
