packages: []

catalogs:
  kitql:
    "@kitql/eslint-config": 0.6.0
    "@kitql/handles": 0.2.4
    "@kitql/helpers": 0.8.12
    "@kitql/internals": 0.10.3
    "@kitql/sveltekit": 0.0.4

  vite: 
    vite-plugin-kit-routes: 0.8.3
    vite-plugin-stripper: 0.9.0
    vite-plugin-watch-and-run: 1.7.4
  
  remult: 
    remult: 3.0.0
    firstly: 0.0.15
  
  devDeps: 
    "@sveltejs/kit": 2.20.0
    "@sveltejs/vite-plugin-svelte": 5.0.3
    node-modules-inspector: 0.6.0
    typescript: 5.8.2
    vite: 6.3.1
