packages: []

catalogs:
 kitql:
  '@kitql/eslint-config': 0.8.0
  '@kitql/handles': 0.3.0
  '@kitql/helpers': 0.8.12
  '@kitql/internals': 0.11.0
  '@kitql/sveltekit': 0.0.4

 vite:
  vite-plugin-kit-routes: 1.0.0
  vite-plugin-stripper: 0.10.0
  vite-plugin-watch-and-run: 1.8.0

 remult:
  remult: 3.3.0
  firstly: 0.4.0

 svelte:
  sv: 0.15.0
  '@sveltejs/sv-utils': 0.2.0

 devDeps:
  '@sveltejs/kit': 2.57.0
  '@sveltejs/vite-plugin-svelte': 7.0.0
  node-modules-inspector: 1.4.2
  typescript: 6.0.2
  vite: 8.0.0
